#!/bin/bash
#
# Program name: reverse
# Author name:  Xinyi Liang
# Date created: April 10, 2020
# Date updated: April 10, 2020
# Description:
#    This script ensures that exactly two parameters are passed. 
#    If so, print the two parameters in reverse order, 
#    otherwise print an error message.

if [ $# != 2 ]
then 
  echo "Error - [Usage]: reverse parm1 parm2" >&2
  exit 1
else
  echo "reverse order output: $2 $1"
fi
